
typedef enum {
  TextureZero = 0,
  TextureOne,
  TextureTwo,
  TextureThree,
  TextureFour,
  TextureFive,
  TextureSix,
  TextureSeven,
  TetxureEight,
  TextureNine,
  TextureBackgroundDay,
  TextureBackgroundNight,
  TextureBase,
  TextureBlueBirdDownFlap,
  TextureBlueBirdMidFlap,
  TextureBlueBirdUpFlap,
  TextureGameover,
  TextureMessage,
  TexturePipeGreen,
  TexturePipeRed,
  TextureRedBirdDownFlap,
  TextureRedBirdMidFlap,
  TextureRedBirdUpFlap,
  TextureYellowBirdDownFlap,
  TextureYellowBirdMidFlap,
  TextureYellowBirdUpFlap,
  _TextureCount_
} GameTextures;

static const char* pngFiles[_TextureCount_] = {
    "0.png",
    "1.png",
    "2.png",
    "3.png",
    "4.png",
    "5.png",
    "6.png",
    "7.png",
    "8.png",
    "9.png",
    "background-day.png",
    "background-night.png",
    "base.png",
    "bluebird-downflap.png",
    "bluebird-midflap.png",
    "bluebird-upflap.png",
    "gameover.png",
    "message.png",
    "pipe-green.png",
    "pipe-red.png",
    "redbird-downflap.png",
    "redbird-midflap.png",
    "redbird-upflap.png",
    "yellowbird-downflap.png",
    "yellowbird-midflap.png",
    "yellowbird-upflap.png",
  };
